version: '{build}'

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
    - devel
  except:
    - gh-pages
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
platform: Any CPU
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    COMPILER: mingw
    TOOLSET: w64-mingw32
    ARCH: i686
    GENERATOR: '"MinGW Makefiles"'
    MINGW_DIR_BIN: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
    CMAKE_C_COMPILER: C:/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/bin/gcc.exe
    CMAKE_CXX_COMPILER: C:/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/bin/g++.exe
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    COMPILER: mingw
    TOOLSET: w64-mingw32
    ARCH: x86_64
    GENERATOR: '"MinGW Makefiles"'
    MINGW_DIR_BIN: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
    CMAKE_C_COMPILER: C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin/gcc.exe
    CMAKE_CXX_COMPILER: C:/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin/g++.exe
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc12
    ARCH: win32
    GENERATOR: '"Visual Studio 12 2013"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc12
    ARCH: win64
    GENERATOR: '"Visual Studio 12 2013 Win64"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc14
    ARCH: win32
    GENERATOR: '"Visual Studio 14 2015"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc14
    ARCH: win64
    GENERATOR: '"Visual Studio 14 2015 Win64"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win32
    GENERATOR: '"Visual Studio 15 2017"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win64
    GENERATOR: '"Visual Studio 15 2017 Win64"'

#---------------------------------#
#            steps                #
#---------------------------------#
install:
  - cmd: git submodule update --init
  - cmd: if [%COMPILER%]==[mingw] (mkdir build-debug)
  - cmd: if [%COMPILER%]==[mingw] (mkdir build-release)
  - cmd: if [%COMPILER%]==[msvc] (mkdir build)
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=%MINGW_DIR_BIN%;%PATH%
  - cmd: if [%COMPILER%]==[mingw] (cd build-debug & cmake .. -G %GENERATOR% -DCMAKE_INSTALL_PREFIX="..\install" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_DEBUG_POSTFIX=_d || exit 1 & cd ..)
  - cmd: if [%COMPILER%]==[mingw] (cd build-release & cmake .. -G %GENERATOR% -DCMAKE_INSTALL_PREFIX="..\install" -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_DEBUG_POSTFIX=_d || exit 1 & cd ..)
  - cmd: if [%COMPILER%]==[msvc] (cd build & cmake .. -G %GENERATOR% -DCMAKE_INSTALL_PREFIX="..\install" -DCMAKE_DEBUG_POSTFIX=_d || exit 1 & cd ..)

build_script:
  - cmd: if [%COMPILER%]==[mingw] (cd build-debug & cmake --build . --target all || exit 1 & cd ..)
  - cmd: if [%COMPILER%]==[mingw] (cd build-release & cmake --build . --target all || exit 1 & cd ..)
  - cmd: if [%COMPILER%]==[msvc] (cd build & cmake --build . --target ALL_BUILD --config Debug || exit 1 & cd ..)
  - cmd: if [%COMPILER%]==[msvc] (cd build & cmake --build . --target ALL_BUILD --config MinSizeRel || exit 1 & cd ..)

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Email
    to:
      - matusnov@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
