compile_gcc: &compile_gcc
  steps:
    - checkout
    - run:
        name: Dependencies
        command: |
          wget https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz
          tar -xvzf cmake-3.10.2-Linux-x86_64.tar.gz
          chmod +x ./cmake-3.10.2-Linux-x86_64/bin/ccmake
          chmod +x ./cmake-3.10.2-Linux-x86_64/bin/cmake
          chmod +x ./cmake-3.10.2-Linux-x86_64/bin/cpack
          chmod +x ./cmake-3.10.2-Linux-x86_64/bin/ctest
          DIR=$(pwd)
          ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/ccmake /usr/bin/ccmake
          ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/cmake /usr/bin/cmake
          ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/cpack /usr/bin/cpack
          ln -s $DIR/cmake-3.10.2-Linux-x86_64/bin/ctest /usr/bin/ctest
          apt-get update
          apt-get install build-essential libgtk-3-dev -y

    - run:
        name: Submodules
        command: |
          git submodule update --init

    - run:
        name: Build
        command: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel
          cmake --build .

version: 2
jobs:
  compile_gcc_550:
    <<: *compile_gcc

    docker:
      - image: gcc:5.5.0

  compile_gcc_650:
    <<: *compile_gcc

    docker:
      - image: gcc:6.5.0
  
  compile_gcc_740:
    <<: *compile_gcc

    docker:
      - image: gcc:7.4.0

  compile_gcc_830:
    <<: *compile_gcc

    docker:
      - image: gcc:8.3.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - compile_gcc_550
      - compile_gcc_650:
          requires:
            - compile_gcc_550
      - compile_gcc_740:
          requires:
            - compile_gcc_650
      - compile_gcc_830:
          requires:
            - compile_gcc_740
